
spring:
  ai:
    openai:
      chat:
        options:

  datasource:
    url: jdbc:mysql://localhost:3306/eadb
    username: root
    password: root
    driver-class: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    root: INFO
server:
  port: 8081


