app:
  name: App
  version: 1.0.0
  url: localhost
  server: sever
  user:
    firstName: John
    lastName: Doe
    userName: john_doe
    password: john_doe
    countries:
      - USA
      - Nepal
      - Peru

server:
  port: 9090

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/eadb
      username: root
      password: root
      driver-class: com.mysql.cj.jdbc.Driver

  jpa:
      hibernate:
          ddl-auto: create
      show-sql: true

logging:
    level:
        root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      show-details: always